from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, field_validator


class AssistantTask(str, Enum):
    EXPLAIN = "explain"
    SIMPLIFY = "simplify"
    GUIDANCE = "guidance"
    QUESTION = "question"


class GroundingCitation(BaseModel):
    """Specific entity or verified fact grounded from the structured recipe context."""
    source_type: str = Field(
        ...,
        description="Source category: 'recipe_directions' | 'pantry_match' | 'curated_substitution' | 'derived_metadata'",
    )
    detail: str = Field(
        ...,
        description="Specific fact, entity, or constraint referenced from the context",
    )


class AssistantRequest(BaseModel):
    """Incoming user request for AI-assisted grounded recipe guidance."""
    recipe_id: int = Field(..., description="Unique ID of the recipe being queried")
    task: AssistantTask = Field(
        default=AssistantTask.QUESTION,
        description="Guidance task: 'explain' | 'simplify' | 'guidance' | 'question'",
    )
    question: Optional[str] = Field(
        default=None,
        max_length=300,
        description="User question for 'question' task (e.g. 'Can I substitute dried basil?'). Max 300 chars.",
    )
    pantry_ingredients: List[str] = Field(
        default_factory=list,
        description="Current user pantry ingredients for context alignment",
    )
    cuisine: Optional[str] = Field(
        default=None,
        description="Optional cuisine preference applied in current session",
    )
    dietary_preference: Optional[str] = Field(
        default=None,
        description="Optional dietary preference applied in current session ('vegetarian' or 'vegan')",
    )
    max_cooking_time_minutes: Optional[int] = Field(
        default=None,
        description="Optional maximum cooking duration limit applied in current session",
    )

    @field_validator("question")
    @classmethod
    def sanitize_question(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return None
        cleaned = v.strip()
        return cleaned if cleaned else None


class StructuredRecipeContext(BaseModel):
    """
    Comprehensive structured context packet assembled by the Entity-Grounded RAG retriever.
    Contains 100% authoritative application data directly from Parquet, SQLite, and Curated Knowledge Base.
    """
    recipe_id: int
    title: str
    ingredients: List[str]
    directions: List[str]
    ner: List[str]
    cuisine: Optional[str] = None
    cuisine_confidence: Optional[str] = None
    dietary_compatibility: Optional[str] = None
    dietary_confidence: Optional[str] = None
    estimated_time_minutes: Optional[int] = None
    time_confidence: Optional[str] = None
    matched_ingredients: List[str] = Field(default_factory=list)
    missing_ingredients: List[str] = Field(default_factory=list)
    ims: float = 0.0
    pus: float = 0.0
    recommendation_score: float = 0.0
    substitutions: List[Dict[str, Any]] = Field(default_factory=list)
    dietary_preference_applied: Optional[str] = None
    cuisine_preference_applied: Optional[str] = None
    max_cooking_time_applied: Optional[int] = None


class AssistantResponse(BaseModel):
    """Natural-language, grounded response from the AI assistant."""
    recipe_id: int
    recipe_title: str
    task: AssistantTask
    answer: str = Field(..., description="Grounded, natural-language guidance or answer")
    citations: List[GroundingCitation] = Field(
        default_factory=list,
        description="Authoritative facts and entities cited in the generated answer",
    )
    substitutions_used: List[str] = Field(
        default_factory=list,
        description="Curated substitutions referenced in the response",
    )
    unsupported_inquiries: List[str] = Field(
        default_factory=list,
        description="Ingredients or elements asked about that have no verified knowledge base data",
    )
    provider: str = Field(..., description="Underlying provider: 'gemini' | 'openai' | 'mock'")
    model: str = Field(..., description="Model identifier used for inference")
    is_mock: bool = Field(..., description="True if generated by local deterministic fallback")


class AssistantStatusResponse(BaseModel):
    """Health and provider status for the AI assistant layer."""
    status: str
    provider: str
    model: str
    is_mock: bool
    has_api_key: bool
