from typing import Dict, List
from backend.app.substitutions.models import SubstitutionEntry

# Curated Culinary Substitution Knowledge Base
# Based on culinary standards from USDA, Culinary Institute of America (CIA),
# and professional culinary kitchen reference guides.

SUBSTITUTION_DATABASE: List[SubstitutionEntry] = [
    # --------------------------------------------------------------------------
    # 1. DAIRY SUBSTITUTIONS
    # --------------------------------------------------------------------------
    SubstitutionEntry(
        original_ingredient="butter",
        substitute="margarine",
        ratio="1:1",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["baking", "cooking", "general"],
        reason="Provides identical fat and moisture content in baking and cooking applications.",
        notes="Use non-hydrogenated, dairy-free stick margarine for baking.",
        source="USDA / CIA Food Standards",
    ),
    SubstitutionEntry(
        original_ingredient="butter",
        substitute="olive oil",
        ratio="1:0.75",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["frying", "cooking", "sauces"],
        reason="Excellent monounsaturated fat replacement in stovetop sauteing, pan-frying, and savory sauces.",
        notes="Use 3/4 cup oil per 1 cup butter to account for liquid density difference.",
        source="Culinary Institute of America",
    ),
    SubstitutionEntry(
        original_ingredient="butter",
        substitute="applesauce",
        ratio="1:0.5",
        confidence="medium",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["baking"],
        reason="Adds moisture and pectin in baked goods (muffins, quick breads) with reduced fat content.",
        notes="Best for dense baked goods like banana bread or brownies.",
        source="USDA Baking Guide",
    ),
    SubstitutionEntry(
        original_ingredient="milk",
        substitute="soy milk",
        ratio="1:1",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["baking", "cooking", "general"],
        reason="Comparable protein, fat, and neutral flavor profile suitable for both savory and sweet dishes.",
        notes="Use unflavored, unsweetened soy milk.",
        source="CIA Plant-Based Culinary Guide",
    ),
    SubstitutionEntry(
        original_ingredient="milk",
        substitute="almond milk",
        ratio="1:1",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["baking", "general"],
        reason="Provides light liquid consistency in sweet baking and smoothies.",
        notes="Slightly thinner body than dairy milk; select unsweetened.",
        source="Culinary Reference Standards",
    ),
    SubstitutionEntry(
        original_ingredient="milk",
        substitute="oat milk",
        ratio="1:1",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["baking", "sauces", "general"],
        reason="Naturally creamy texture and mild oat sweetness that emulates dairy mouthfeel well.",
        notes="Performs exceptionally well in custards, puddings, and creamy soups.",
        source="CIA Plant-Based Culinary Guide",
    ),
    SubstitutionEntry(
        original_ingredient="heavy cream",
        substitute="milk and melted butter",
        ratio="1:1",
        confidence="high",
        dietary_compatibility=["vegetarian"],
        use_cases=["cooking", "sauces", "baking"],
        reason="Emulsifying 3/4 cup whole milk with 1/4 cup melted butter reconstructs the 36% fat ratio of heavy cream.",
        notes="Suitable for pan sauces and casseroles; cannot be whipped into stiff peaks.",
        source="Gisslen Professional Cooking",
    ),
    SubstitutionEntry(
        original_ingredient="heavy cream",
        substitute="coconut cream",
        ratio="1:1",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["cooking", "sauces", "baking", "general"],
        reason="Rich, saturated plant-fat emulsion providing luxurious body and thickening power in savory curries and desserts.",
        notes="Adds a subtle coconut aroma; chills and whips effectively.",
        source="CIA Plant-Based Culinary Guide",
    ),
    SubstitutionEntry(
        original_ingredient="sour cream",
        substitute="plain greek yogurt",
        ratio="1:1",
        confidence="high",
        dietary_compatibility=["vegetarian"],
        use_cases=["general", "baking", "sauces"],
        reason="Matches the tangy acidity, cultured richness, and thick viscosity of sour cream with higher protein.",
        notes="Ideal as a taco topping, dip base, or baking ingredient.",
        source="USDA Nutrition & Culinary Guide",
    ),
    SubstitutionEntry(
        original_ingredient="sour cream",
        substitute="silken tofu with lemon juice",
        ratio="1:1",
        confidence="medium",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["sauces", "dips", "general"],
        reason="Pureed silken tofu blended with 1 tbsp lemon juice recreates smooth acidic creaminess without dairy.",
        notes="Blend thoroughly in food processor until completely glossy.",
        source="CIA Plant-Based Culinary Guide",
    ),
    SubstitutionEntry(
        original_ingredient="buttermilk",
        substitute="milk with lemon juice or vinegar",
        ratio="1:1",
        confidence="high",
        dietary_compatibility=["vegetarian"],
        use_cases=["baking", "general"],
        reason="Adding 1 tbsp lemon juice or white vinegar to 1 cup milk creates lactic-style acid curds that activate baking soda.",
        notes="Let stand for 5 minutes before mixing into batter.",
        source="Joy of Cooking Standards",
    ),
    SubstitutionEntry(
        original_ingredient="buttermilk",
        substitute="soy milk with lemon juice",
        ratio="1:1",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["baking", "general"],
        reason="Curdles readily to provide identical chemical leavening acidity in vegan pancakes, biscuits, and waffles.",
        notes="Let stand 5 minutes until curdled.",
        source="CIA Plant-Based Culinary Guide",
    ),
    SubstitutionEntry(
        original_ingredient="parmesan cheese",
        substitute="pecorino romano",
        ratio="1:1",
        confidence="high",
        dietary_compatibility=["vegetarian"],
        use_cases=["general", "cooking", "sauces"],
        reason="Aged sheep's milk hard cheese providing identical savory umami, crystalline texture, and grateability.",
        notes="Pecorino is slightly saltier; adjust recipe salt downward.",
        source="Italian Culinary Standards",
    ),
    SubstitutionEntry(
        original_ingredient="parmesan cheese",
        substitute="nutritional yeast",
        ratio="1:0.5",
        confidence="medium",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["general", "salads", "sauces"],
        reason="Deactivated yeast flakes containing natural glutamates providing cheesy, savory depth and yellow tint.",
        notes="Use half the volume; excellent sprinkled on popcorn, pasta, and roasted vegetables.",
        source="CIA Plant-Based Culinary Guide",
    ),
    SubstitutionEntry(
        original_ingredient="cheddar cheese",
        substitute="monterey jack cheese",
        ratio="1:1",
        confidence="high",
        dietary_compatibility=["vegetarian"],
        use_cases=["general", "cooking", "baking"],
        reason="Semi-hard cow's milk cheese offering similar meltability, moisture, and mild sharpness.",
        notes="Great for nachos, quesadillas, burgers, and gratins.",
        source="Wisconsin Cheese Culinary Board",
    ),
    SubstitutionEntry(
        original_ingredient="ricotta cheese",
        substitute="cottage cheese (strained)",
        ratio="1:1",
        confidence="high",
        dietary_compatibility=["vegetarian"],
        use_cases=["general", "baking", "cooking"],
        reason="Similar milk-curd composition; pureeing strained cottage cheese closely replicates ricotta's creamy texture.",
        notes="Blend in a food processor to break up large curds before assembling lasagna or manicotti.",
        source="USDA Culinary Standards",
    ),
    SubstitutionEntry(
        original_ingredient="yogurt",
        substitute="sour cream",
        ratio="1:1",
        confidence="high",
        dietary_compatibility=["vegetarian"],
        use_cases=["general", "baking", "sauces"],
        reason="Delivers equivalent lactic acidity and richness in marinades, dips, and quick breads.",
        notes="Sour cream has higher fat; adjust moisture slightly if baking delicate cakes.",
        source="Culinary Institute of America",
    ),
    SubstitutionEntry(
        original_ingredient="yogurt",
        substitute="coconut yogurt",
        ratio="1:1",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["general", "baking", "sauces"],
        reason="Cultured plant milk yogurt offering similar tartness and creamy mouthfeel without dairy.",
        notes="Select plain, unsweetened varieties for savory marinades.",
        source="CIA Plant-Based Culinary Guide",
    ),

    # --------------------------------------------------------------------------
    # 2. EGGS
    # --------------------------------------------------------------------------
    SubstitutionEntry(
        original_ingredient="egg",
        substitute="flaxseed meal mixed with water (flax egg)",
        ratio="1:1 egg = 1 tbsp flax + 3 tbsp water",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["baking", "binding"],
        reason="Soluble fiber in ground flax mucilage binds moisture and provides structural integrity during oven heat.",
        notes="Let sit for 5 minutes until gelatinous. Ideal for cookies, brownies, and muffins.",
        source="CIA Plant-Based Culinary Guide",
    ),
    SubstitutionEntry(
        original_ingredient="egg",
        substitute="applesauce",
        ratio="1:1 egg = 0.25 cup applesauce",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["baking"],
        reason="Pectin and natural carbohydrates retain moisture and bind starch particles in baked cakes and quick breads.",
        notes="Add 1/2 tsp baking powder if additional leavening is needed.",
        source="USDA Baking Guide",
    ),
    SubstitutionEntry(
        original_ingredient="egg",
        substitute="mashed banana",
        ratio="1:1 egg = 0.5 ripe banana",
        confidence="medium",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["baking"],
        reason="Rich in starches and moisture that hold batters together during baking.",
        notes="Imparts noticeable banana flavor; best for pancakes, muffins, and sweet breads.",
        source="Baking Reference Standards",
    ),

    # --------------------------------------------------------------------------
    # 3. FATS AND OILS
    # --------------------------------------------------------------------------
    SubstitutionEntry(
        original_ingredient="olive oil",
        substitute="vegetable oil",
        ratio="1:1",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["cooking", "frying", "general"],
        reason="Neutral vegetable oil handles equal cooking heat and maintains moisture across stovetop recipes.",
        notes="Neutral flavor profile; best when strong olive fruitiness is not essential.",
        source="CIA Professional Chef",
    ),
    SubstitutionEntry(
        original_ingredient="vegetable oil",
        substitute="canola oil",
        ratio="1:1",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["cooking", "frying", "baking", "general"],
        reason="Direct 1:1 substitute with identical smoke point (400°F/204°C) and neutral flavor.",
        notes="Interchangeable in virtually all cooking and baking recipes.",
        source="USDA Cooking Oil Standards",
    ),
    SubstitutionEntry(
        original_ingredient="vegetable oil",
        substitute="applesauce",
        ratio="1:0.75",
        confidence="medium",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["baking"],
        reason="Replaces oil with fruit moisture in cakes and brownies for a low-fat alternative.",
        notes="Produces a denser crumb; reduce bake time by 5-8 minutes.",
        source="USDA Baking Guide",
    ),

    # --------------------------------------------------------------------------
    # 4. ACIDIC INGREDIENTS
    # --------------------------------------------------------------------------
    SubstitutionEntry(
        original_ingredient="lemon juice",
        substitute="lime juice",
        ratio="1:1",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["cooking", "salads", "sauces", "general"],
        reason="Identical citric acid concentration (approx. 5%) and brightness for balance.",
        notes="Lime has slight tropical floral notes but performs identically in vinaigrettes and marinades.",
        source="CIA Kitchen Essentials",
    ),
    SubstitutionEntry(
        original_ingredient="lemon juice",
        substitute="apple cider vinegar",
        ratio="1:0.5",
        confidence="medium",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["cooking", "sauces", "marinades"],
        reason="Fruity acetic acid profile provides necessary tartness and pH lowering in cooked dishes.",
        notes="Use half quantity due to acetic sharpness compared to citric acid.",
        source="Culinary Institute of America",
    ),
    SubstitutionEntry(
        original_ingredient="lime juice",
        substitute="lemon juice",
        ratio="1:1",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["cooking", "salads", "sauces", "general"],
        reason="Equivalent citrus acidity and freshness for guacamole, ceviche, dressings, and drinks.",
        notes="Universal 1:1 citrus substitution.",
        source="CIA Kitchen Essentials",
    ),
    SubstitutionEntry(
        original_ingredient="white wine",
        substitute="vegetable broth with lemon juice",
        ratio="1:1 wine = 1 cup broth + 1 tbsp lemon juice",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["cooking", "sauces"],
        reason="Replaces cooking wine volume with savory broth while lemon juice mimics wine's natural acidity.",
        notes="Deglazes pans and enriches risottos effectively without alcohol.",
        source="Escoffier Culinary Standards",
    ),
    SubstitutionEntry(
        original_ingredient="apple cider vinegar",
        substitute="white vinegar with apple juice",
        ratio="1:1 vinegar = 1 tbsp white vinegar + 1 tsp apple juice",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["cooking", "sauces", "general"],
        reason="Recreates apple cider vinegar's sweet-tart acetic balance and fruity notes.",
        notes="Ideal for pickling brines, barbecue sauces, and marinades.",
        source="Culinary Reference Standards",
    ),

    # --------------------------------------------------------------------------
    # 5. THICKENING AGENTS
    # --------------------------------------------------------------------------
    SubstitutionEntry(
        original_ingredient="cornstarch",
        substitute="all-purpose flour",
        ratio="1:2 (1 tbsp cornstarch = 2 tbsp flour)",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["sauces", "cooking"],
        reason="Wheat starch gelatinizes under heat to thicken soups, gravies, and fillings.",
        notes="Flour requires simmering for at least 2-3 minutes to eliminate raw flour taste.",
        source="CIA Professional Chef",
    ),
    SubstitutionEntry(
        original_ingredient="cornstarch",
        substitute="arrowroot powder",
        ratio="1:1",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["sauces", "cooking"],
        reason="Pure plant starch that yields a crystal-clear glaze with no starchy aftertaste.",
        notes="Excellent for acidic liquids and fruit pies; do not overboil or it thins.",
        source="CIA Kitchen Essentials",
    ),
    SubstitutionEntry(
        original_ingredient="all-purpose flour",
        substitute="cornstarch (for thickening)",
        ratio="1:0.5 (2 tbsp flour = 1 tbsp cornstarch)",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["sauces", "cooking"],
        reason="Cornstarch has twice the thickening power of wheat flour and creates a glossy finish.",
        notes="Always whisk into cold water first to form a slurry before adding to hot liquid.",
        source="CIA Professional Chef",
    ),

    # --------------------------------------------------------------------------
    # 6. HERBS AND AROMATICS
    # --------------------------------------------------------------------------
    SubstitutionEntry(
        original_ingredient="garlic",
        substitute="garlic powder",
        ratio="1:1 clove = 0.125 tsp powder",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["cooking", "sauces", "general"],
        reason="Dehydrated, pulverized allium delivering concentrated allicin flavor compounds evenly throughout dishes.",
        notes="Distributes evenly in dry rubs and marinades without burning.",
        source="USDA Spice & Herb Standards",
    ),
    SubstitutionEntry(
        original_ingredient="garlic",
        substitute="shallots",
        ratio="1:1 clove = 0.5 shallot",
        confidence="medium",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["cooking", "sauces"],
        reason="Offers delicate onion-garlic aroma and mild sweetness when sauteed.",
        notes="Adds texture and sweetness; less pungent than fresh garlic.",
        source="French Culinary Standards",
    ),
    SubstitutionEntry(
        original_ingredient="onion",
        substitute="onion powder",
        ratio="1:1 medium onion = 1 tbsp powder",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["cooking", "sauces", "general"],
        reason="Provides concentrated onion aromatic depth and umami without adding moisture or bulk.",
        notes="Great in meatballs, burger patties, sauces, and spice blends.",
        source="USDA Spice & Herb Standards",
    ),
    SubstitutionEntry(
        original_ingredient="onion",
        substitute="shallots",
        ratio="1:1",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["cooking", "sauces", "general"],
        reason="Belongs to the same allium family with sweet, subtle pungency suitable for sautés and dressings.",
        notes="Milder and melts more completely into pan sauces.",
        source="CIA Kitchen Essentials",
    ),
    SubstitutionEntry(
        original_ingredient="fresh basil",
        substitute="dried basil",
        ratio="1:0.33 (1 tbsp fresh = 1 tsp dried)",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["cooking", "sauces"],
        reason="Concentrated essential oils in dried herbs infuse flavor into cooked tomato sauces and stews.",
        notes="Add early in cooking to allow dried herb leaves to rehydrate.",
        source="CIA Herb Reference Guide",
    ),
    SubstitutionEntry(
        original_ingredient="fresh oregano",
        substitute="dried oregano",
        ratio="1:0.33 (1 tbsp fresh = 1 tsp dried)",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["cooking", "sauces", "general"],
        reason="Oregano is one of the few herbs where dried form is robust and deeply aromatic.",
        notes="Standard in tomato sauces, pizza toppings, and Greek marinades.",
        source="Mediterranean Culinary Standards",
    ),
    SubstitutionEntry(
        original_ingredient="fresh ginger",
        substitute="ground ginger",
        ratio="1:1 tbsp fresh = 0.25 tsp ground",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["cooking", "baking", "sauces"],
        reason="Dehydrated zingiberene provides sharp ginger heat and warm spice notes.",
        notes="Spicier and less citrusy than fresh root; adjust carefully.",
        source="CIA Asian Culinary Standards",
    ),
    SubstitutionEntry(
        original_ingredient="cilantro",
        substitute="flat-leaf parsley with lime zest",
        ratio="1:1",
        confidence="medium",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["salads", "cooking", "general"],
        reason="Parsley matches cilantro's leafy texture and herbaceous green color while lime zest supplies citrus top-notes.",
        notes="Popular alternative for individuals sensitive to aldehyde compounds in cilantro.",
        source="Culinary Institute of America",
    ),

    # --------------------------------------------------------------------------
    # 7. PANTRY STAPLES & SWEETENERS
    # --------------------------------------------------------------------------
    SubstitutionEntry(
        original_ingredient="brown sugar",
        substitute="white granulated sugar with molasses",
        ratio="1:1 cup = 1 cup white sugar + 1 tbsp molasses",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["baking", "cooking", "general"],
        reason="Commercial brown sugar is simply granulated white sugar mixed with cane molasses.",
        notes="Use 2 tbsp molasses for dark brown sugar equivalent.",
        source="USDA Sugar Standards",
    ),
    SubstitutionEntry(
        original_ingredient="brown sugar",
        substitute="white granulated sugar",
        ratio="1:1",
        confidence="medium",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["baking", "general"],
        reason="Supplies identical sucrose sweetness and crystalline structure in cookies and cakes.",
        notes="Cookies will be slightly crispier and lighter in color with less caramel undertone.",
        source="Baking Culinary Standards",
    ),
    SubstitutionEntry(
        original_ingredient="honey",
        substitute="maple syrup",
        ratio="1:1",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["general", "baking", "cooking"],
        reason="Natural liquid sweetener offering comparable viscosity, moisture, and caramelized notes without bee products.",
        notes="Ideal vegan liquid sweetener replacement.",
        source="CIA Plant-Based Culinary Guide",
    ),
    SubstitutionEntry(
        original_ingredient="honey",
        substitute="agave nectar",
        ratio="1:1",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["general", "baking", "cooking"],
        reason="Mild liquid sweetener with high fructose content that dissolves easily in hot or cold recipes.",
        notes="Slightly sweeter than honey; neutral amber profile.",
        source="Culinary Reference Standards",
    ),
    SubstitutionEntry(
        original_ingredient="chicken broth",
        substitute="vegetable broth",
        ratio="1:1",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["cooking", "sauces", "general"],
        reason="Simmered root vegetable stock (mirepoix) provides savory foundation and umami depth without animal products.",
        notes="Universally compatible in soups, risottos, and braises.",
        source="CIA Kitchen Essentials",
    ),
    SubstitutionEntry(
        original_ingredient="chicken broth",
        substitute="water with butter and herbs",
        ratio="1:1 cup = 1 cup water + 1 tbsp butter + pinch herbs",
        confidence="medium",
        dietary_compatibility=["vegetarian"],
        use_cases=["cooking"],
        reason="Adds fat and aromatics to cooking liquid when prepared stock is unavailable.",
        notes="Season with salt, black pepper, and thyme or parsley.",
        source="Professional Kitchen Reference",
    ),
    SubstitutionEntry(
        original_ingredient="beef broth",
        substitute="vegetable broth with soy sauce",
        ratio="1:1 cup = 1 cup vegetable broth + 1 tsp soy sauce",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["cooking", "sauces", "general"],
        reason="Soy sauce infuses roasted amino acids and dark color that simulate deep beef stock fond.",
        notes="Use low-sodium soy sauce to avoid over-salting.",
        source="CIA Plant-Based Culinary Guide",
    ),
    SubstitutionEntry(
        original_ingredient="soy sauce",
        substitute="tamari",
        ratio="1:1",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["general", "cooking", "sauces"],
        reason="Brewed with whole soybeans, providing deeper umami and gluten-free compatibility.",
        notes="Slightly richer flavor; excellent for stir-fries and dressings.",
        source="Japanese Culinary Reference",
    ),
    SubstitutionEntry(
        original_ingredient="soy sauce",
        substitute="coconut aminos",
        ratio="1:1",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["general", "cooking", "sauces"],
        reason="Fermented coconut blossom nectar providing savory salty-sweet notes with lower sodium.",
        notes="Slightly sweeter than traditional soy sauce.",
        source="Culinary Health Reference",
    ),
    SubstitutionEntry(
        original_ingredient="tomato sauce",
        substitute="tomato paste mixed with water",
        ratio="1:1 sauce = 1 part paste + 1 part water",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["cooking", "sauces", "general"],
        reason="Reconstituting concentrated cooked tomato puree recreates standard canned tomato sauce viscosity.",
        notes="Season with a pinch of salt and dried oregano if desired.",
        source="Italian Culinary Standards",
    ),
    SubstitutionEntry(
        original_ingredient="tomato sauce",
        substitute="crushed canned tomatoes pureed",
        ratio="1:1",
        confidence="high",
        dietary_compatibility=["vegetarian", "vegan"],
        use_cases=["cooking", "sauces", "general"],
        reason="Pureed whole peeled or crushed canned tomatoes provide fresh, rich tomato body.",
        notes="Simmer 5 minutes to reduce slightly if thinner than jarred sauce.",
        source="CIA Kitchen Essentials",
    ),
]

# Build fast in-memory normalized index for ingredient lookup
# Maps canonical ingredient name -> List[SubstitutionEntry]
_SUBSTITUTION_INDEX: Dict[str, List[SubstitutionEntry]] = {}

for entry in SUBSTITUTION_DATABASE:
    key = entry.original_ingredient.lower().strip()
    if key not in _SUBSTITUTION_INDEX:
        _SUBSTITUTION_INDEX[key] = []
    _SUBSTITUTION_INDEX[key].append(entry)


def get_substitutions_for_ingredient(ingredient_name: str) -> List[SubstitutionEntry]:
    """
    Lookup substitution candidates for a given ingredient name.
    Performs case-insensitive matching and plural/singular stripping.
    """
    if not ingredient_name:
        return []

    norm = ingredient_name.lower().strip()

    # Exact match in index
    if norm in _SUBSTITUTION_INDEX:
        return _SUBSTITUTION_INDEX[norm]

    # Check singularized form (e.g. 'eggs' -> 'egg', 'shallots' -> 'shallot')
    if norm.endswith("s") and norm[:-1] in _SUBSTITUTION_INDEX:
        return _SUBSTITUTION_INDEX[norm[:-1]]

    # Substring search for multi-word ingredients (e.g. 'unsalted butter' -> 'butter')
    for key, entries in _SUBSTITUTION_INDEX.items():
        if key in norm or norm in key:
            return entries

    return []
